# Generated by Django 5.2.18 on 2026-10-08 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('calculated', 'Calculated'), ('approved', 'Approved'), ('finalized', 'Finalized'), ('reopened', 'Reopened')], default='open', max_length=20)),
                ('divisor_mode', models.CharField(blank=True, max_length=40)),
                ('policy_fingerprint', models.CharField(blank=True, max_length=64)),
                ('needs_recalculation', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('reopen_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_approvals', to=settings.AUTH_USER_MODEL)),
                ('calculated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_calculations', to=settings.AUTH_USER_MODEL)),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_finalizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_type', models.CharField(max_length=20)),
                ('scheduled_working_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('present_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('absent_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('half_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('paid_leave_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('unpaid_leave_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('weekly_offs', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('public_holidays', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('late_count', models.PositiveIntegerField(default=0)),
                ('late_minutes', models.PositiveIntegerField(default=0)),
                ('early_departures', models.PositiveIntegerField(default=0)),
                ('working_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('allowances_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bonuses_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('approved_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unpaid_leave_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('attendance_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('late_penalty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('advances_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_adjustments', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('unpaid', 'Unpaid'), ('partially_paid', 'Partially paid'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=40)),
                ('payment_reference', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('advances_applied', models.BooleanField(default=False)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_records', to='employees.employee')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='payroll.payrollperiod')),
            ],
            options={
                'ordering': ['employee__employee_code'],
            },
        ),
        migrations.CreateModel(
            name='PayrollLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('earning', 'Earning'), ('deduction', 'Deduction')], max_length=20)),
                ('code', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_manual', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='payroll.payrollrecord')),
            ],
            options={
                'ordering': ['kind', 'code', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SalaryAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remaining', models.DecimalField(decimal_places=2, max_digits=12)),
                ('issued_date', models.DateField()),
                ('monthly_recovery', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('recovered', 'Recovered'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advances', to='employees.employee')),
            ],
            options={
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='AdvanceRecovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payroll_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_recoveries', to='payroll.payrollrecord')),
                ('advance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recoveries', to='payroll.salaryadvance')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_on', models.DateField()),
                ('method', models.CharField(max_length=40)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payroll.payrollrecord')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-paid_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('label', models.CharField(default='Bonus', max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bonuses', to='employees.employee')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='bonus_positive')],
            },
        ),
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('label', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deductions', to='employees.employee')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='deduction_positive')],
            },
        ),
        migrations.AddConstraint(
            model_name='payrollperiod',
            constraint=models.UniqueConstraint(fields=('year', 'month'), name='uniq_payroll_period'),
        ),
        migrations.AddConstraint(
            model_name='payrollperiod',
            constraint=models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='payroll_month_range'),
        ),
        migrations.AddIndex(
            model_name='payrollrecord',
            index=models.Index(fields=['payment_status'], name='payroll_pay_payment_ff25e8_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollrecord',
            constraint=models.UniqueConstraint(fields=('period', 'employee'), name='uniq_payroll_employee_period'),
        ),
        migrations.AddConstraint(
            model_name='salaryadvance',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='advance_positive'),
        ),
        migrations.AddConstraint(
            model_name='salaryadvance',
            constraint=models.CheckConstraint(condition=models.Q(('remaining__gte', 0)), name='advance_remaining_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='advancerecovery',
            constraint=models.UniqueConstraint(fields=('payroll_record', 'advance'), name='uniq_advance_recovery'),
        ),
        migrations.AddConstraint(
            model_name='salarypayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_positive'),
        ),
    ]
