# Generated by Django 5.2.18 on 2026-10-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super user'), ('management', 'Management'), ('employee', 'Employee'), ('hr_manager', 'HR Manager'), ('accountant', 'Accountant'), ('department_manager', 'Department Manager')], default='employee', max_length=32),
        ),
    ]
