# Generated by Django 5.2.18 on 2026-10-08 13:43

import apps.organization.models
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('address', models.TextField(blank=True)),
                ('timezone', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OfficeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Harbor & Co.', max_length=200)),
                ('legal_name', models.CharField(blank=True, max_length=200)),
                ('timezone', models.CharField(default='Asia/Karachi', max_length=64)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('standard_work_minutes', models.PositiveIntegerField(default=480)),
                ('default_grace_minutes', models.PositiveIntegerField(default=10)),
                ('early_departure_grace_minutes', models.PositiveIntegerField(default=10)),
                ('half_day_threshold_minutes', models.PositiveIntegerField(default=240)),
                ('monthly_late_warning_threshold', models.PositiveIntegerField(default=3)),
                ('overtime_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=5)),
                ('holiday_work_counts_as_overtime', models.BooleanField(default=True)),
                ('salary_divisor_mode', models.CharField(choices=[('calendar_days', 'Calendar days'), ('scheduled_working_days', 'Scheduled working days'), ('fixed', 'Fixed divisor')], default='scheduled_working_days', max_length=40)),
                ('fixed_salary_divisor', models.DecimalField(decimal_places=2, default=Decimal('30'), max_digits=6)),
                ('unpaid_leave_deduction_enabled', models.BooleanField(default=True)),
                ('absence_deduction_enabled', models.BooleanField(default=False)),
                ('late_penalty_enabled', models.BooleanField(default=False)),
                ('late_penalty_mode', models.CharField(choices=[('per_occurrence', 'Per late arrival'), ('per_minute', 'Per late minute')], default='per_occurrence', max_length=32)),
                ('late_penalty_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('daily_wage_pays_weekly_off', models.BooleanField(default=False)),
                ('daily_wage_pays_holiday', models.BooleanField(default=False)),
                ('daily_wage_pays_paid_leave', models.BooleanField(default=True)),
                ('self_checkin_enabled', models.BooleanField(default=True)),
                ('biometric_enabled', models.BooleanField(default=False)),
                ('default_weekly_off_days', models.JSONField(default=apps.organization.models.default_weekly_offs)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Office settings',
                'verbose_name_plural': 'Office settings',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('break_minutes', models.PositiveIntegerField(default=60)),
                ('grace_minutes', models.PositiveIntegerField(default=10)),
                ('early_grace_minutes', models.PositiveIntegerField(default=10)),
                ('is_overnight', models.BooleanField(default=False)),
                ('timezone', models.CharField(blank=True, max_length=64)),
                ('weekly_off_days', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='organization.officelocation')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_titles', to='organization.department')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'department'), name='uniq_job_title_department')],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='organization.officelocation')),
            ],
            options={
                'ordering': ['date', 'name'],
                'indexes': [models.Index(fields=['date'], name='organizatio_date_bb64b4_idx')],
            },
        ),
    ]
