# Generated by Django 5.2.18 on 2026-10-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officesettings',
            name='company_name',
            field=models.CharField(default='Wesolucions', max_length=200),
        ),
    ]
