# Generated by Django 5.2.18 on 2026-10-08 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_paid', models.BooleanField(default=True)),
                ('tracks_balance', models.BooleanField(default=True)),
                ('annual_entitlement', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('allow_negative', models.BooleanField(default=False)),
                ('color', models.CharField(default='#0f766e', max_length=20)),
                ('requires_document', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('day_part', models.CharField(choices=[('full', 'Full day'), ('first_half', 'First half'), ('second_half', 'Second half')], default='full', max_length=20)),
                ('total_days', models.DecimalField(decimal_places=2, max_digits=6)),
                ('reason', models.TextField()),
                ('document', models.FileField(blank=True, null=True, upload_to='leave-documents/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('review_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to='employees.employee')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_reviews', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='leaves.leavetype')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'start_date'], name='leaves_leav_status_bca0ae_idx'), models.Index(fields=['employee', 'start_date'], name='leaves_leav_employe_7c5f34_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('entitled', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('used', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('pending', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='employees.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='leaves.leavetype')),
            ],
            options={
                'ordering': ['leave_type__name'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'leave_type', 'year'), name='uniq_leave_balance'), models.CheckConstraint(condition=models.Q(('entitled__gte', 0)), name='leave_entitled_nonnegative'), models.CheckConstraint(condition=models.Q(('used__gte', 0)), name='leave_used_nonnegative'), models.CheckConstraint(condition=models.Q(('pending__gte', 0)), name='leave_pending_nonnegative')],
            },
        ),
    ]
